about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),

]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('groups/', views.groups, name='groups'),
    path('authors/', views.authors_list, name='authors_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/like/', views.post_like, name='post_like'),
    path('posts/<int:post_id>/unlike/', views.post_unlike, name='post_unlike'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'comment/<int:comment_id>/del',
        views.del_comment,
        name='del_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('search/', views.search, name='search_results'),
    path('tag/<tag_slug>', views.index, name='index_by_tag'),
    path('', views.index, name='index'),

]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'profile/',
        views.user_profile,
        name='user_profile'
    ),
    path(
        'signup/',
        views.SignUp.as_view(template_name='users/signup.html'),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/includes/footer.html
<footer  id="footer" class="footer border-top py-3 text-center">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="32"
             height="32"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ruslan</span>bers 
      </a>
      <form class="row g-3" method="get" action="{% url 'posts:search_results' %}">
        <div class="col-auto">
          <input class="form-control" name="q" type="text" placeholder="Поиск по записям">
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-primary">
            <svg class="i-search" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-width="2">
              <circle cx="14" cy="14" r="12" />
              <path d="M23 23 L30 30"  />
            </svg>
          </button>
        </div>
      </form>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:tech' %} active {% endif %}"
               href="{% url 'about:tech' %}">О проекте</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'posts:post_create' %} active {% endif %}"
                 href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            <li>
              <div class="dropdown">
                <a class="nav-link active dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  Пользователь: {{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li>
                    <a class="dropdown-item" href="{% url 'posts:profile' request.user %}">
                      Моя страница
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'users:user_profile' %}">
                      Личный кабинет
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'users:password_change' %}">
                      Изменить пароль
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                      Выйти
                    </a>
                  </li>
                </ul>
              </div>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'users:login' %} active {% endif %} link-light"
                 href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'users:signup' %} active {% endif %} link-light"
                 href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
            
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>