about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),

]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('groups/', views.groups, name='groups'),
    path('authors/', views.authors_list, name='authors_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/like/', views.post_like, name='post_like'),
    path('posts/<int:post_id>/unlike/', views.post_unlike, name='post_unlike'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'comment/<int:comment_id>/del',
        views.del_comment,
        name='del_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('search/', views.search, name='search_results'),
    path('tag/<tag_slug>', views.index, name='index_by_tag'),
    path('', views.index, name='index'),

]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from taggit.managers import TaggableManager


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=20, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'
        ordering = ('title',)


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.text[:settings.POST_STRING_TITLE]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:settings.POST_STRING_TITLE]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    def __str__(self):
        return f'{self.user} -> {self.author.username}'

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        unique_together = ['user', 'author']


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='liker',
        verbose_name='Пользователь',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='liked',
        verbose_name='Пост'
    )

    def __str__(self):
        return f'{self.user} -> {self.post}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'
        unique_together = ['user', 'post']

posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'tags', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class SearchForm(forms.Form):
    text = forms.CharField(max_length=50)

posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from taggit.models import Tag

from .utils import get_posts_context, get_authors_context
from .forms import CommentForm, PostForm
from .models import Comment, Group, Follow, Like, Post, User


@cache_page(settings.INDEX_CACHE_TIMEOUT, key_prefix="index_page")
def index(request, tag_slug=None):
    posts = Post.objects.select_related('group', 'author')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    context = get_posts_context(posts, request)
    context['tag'] = tag
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/index.html', context)


def search(request):
    search = request.GET.get('q')
    context = get_posts_context(
        Post.objects.select_related('group', 'author').filter(
            text__icontains=search
        ),
        request
    )
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/index.html', context)


@login_required
def follow_index(request):
    context = get_posts_context(
        Post.objects.filter(
            author__following__user=request.user
        ).select_related('group'),
        request
    )
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/follow.html', context)


def groups(request):
    groups = Group.objects.all()
    return render(request, 'posts/groups_all.html', {"page_obj": groups})


def authors_list(request):
    authors = User.objects.annotate(posts_qty=Count('posts')).order_by(
        '-posts_qty'
    ).exclude(username__in=('admin', 'superadmin'))
    context = get_authors_context(authors, request)
    context['posts_king'] = authors[0]
    context['comments_king'] = User.objects.annotate(
        comments_qty=Count('comments')).order_by('-comments_qty')[0]
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/authors_list.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(
        get_posts_context(
            group.posts.select_related('author'),
            request
        )
    )
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    context = {
        'author': author,
    }
    context.update(
        get_posts_context(author.posts.select_related('group'), request)
    )
    if request.user.is_authenticated:
        context['following'] = request.user.follower.filter(
            author=author).exists()
    context['tags_colors'] = settings.TAGS_COLORS
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('group', 'author'),
        id=post_id
    )
    comments = post.comments.all()
    form = CommentForm()
    liked = (request.user.is_authenticated
             and request.user.liker.filter(post=post).exists())
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'liked': liked,
        'tags_colors': settings.TAGS_COLORS,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        form.save_m2m()
        return redirect('posts:profile', post.author.username)

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    if author != request.user:
        return redirect('posts:post_detail', post_id)
    else:
        post.delete()
        return redirect('posts:profile', author.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        form.save_m2m()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if (post.author != request.user
            and not request.user.liker.filter(post=post).exists()):
        Like.objects.create(
            user=request.user,
            post=post
        )
    return redirect('posts:post_detail', post_id)


@login_required
def post_unlike(request, post_id):
    Like.objects.filter(
        post=get_object_or_404(Post, id=post_id),
        user=request.user
    ).delete()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def del_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    author = comment.author
    if author != request.user:
        return redirect('posts:post_detail', comment.post.id)
    else:
        comment.delete()
    return redirect('posts:post_detail', comment.post.id)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (author != request.user
            and not request.user.follower.filter(author=author).exists()):
        Follow.objects.create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        author=get_object_or_404(User, username=username),
        user=request.user
    ).delete()
    return redirect('posts:profile', username)

templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">
        Первая
      </a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a> 
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% elif i >= page_obj.number|add:-3 and i <= page_obj.number|add:3 %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

templates/posts/includes/post_card.html
{% load thumbnail %}
{% load static %}
<div class="row border rounded mb-4 shadow-sm">
  <div class="col p-4 flex-column">
    <div class="row">
      <div class="col-auto">
        {% if post.author.profile.photo %}
          {% thumbnail post.author.profile.photo "60x60" crop="center" as photo %}
          <img class="img-fluid rounded mx-auto" src="{{ photo.url }}">
          {% endthumbnail %}
        {% else %}
          <img src="{% static 'img/avatar.jpg' %}" width="60" height="60" class="d-inline-block" alt="">
        {% endif %}
      </div>
      <div class="col-auto col-md-6">
        Автор: 
        <a href="{% url 'posts:profile' post.author.username %}"> 
          {% if post.author.get_full_name %} 
            {{ post.author.get_full_name }} 
          {% else %} 
            {{ post.author.username }}
          {% endif %}
        </a><br>
        <small>Дата публикации: {{ post.pub_date|date:"j M Y" }}</small><br>
        {% if post.group and group_link %} 
          <small>
            Группа: 
            <a href="{% url 'posts:group_list' post.group.slug %}" title="все записи группы">
              {{ post.group.title }}
            </a>
          </small>
        {% endif %}
      </div>
    </div>

    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr|truncatechars:200 }}</p>
    <p> 
      {% if post.tags.exists %} 
        Теги:
        {% for tag in post.tags.all %}
          <a class="btn btn-{{ tags_colors|random }} btn-sm" href="{% url "posts:index_by_tag" tag.slug %}">
              {{ tag.name }}
          </a>
        {% endfor %}
      {% endif %}
    </p>
    <div class="row">
      <div class="col">
        <a class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.id %}#like" title="Нравится">
          <svg class="i-heart" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
            <path d="M4 16 C1 12 2 6 7 4 12 2 15 6 16 8 17 6 21 2 26 4 31 6 31 12 28 16 25 20 16 28 16 28 16 28 7 20 4 16 Z" />
          </svg> {{ post.liked.count }}
        </a>
        <a class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.id %}#readcomment" title="Читать комментарии">
          <svg class="i-msg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
            <path d="M2 4 L30 4 30 22 16 22 8 29 8 22 2 22 Z" />
          </svg> {{ post.comments.count }}
        </a>
      </div>
      <div class="col-auto">
        <a class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.id %}" title="подробная информация">
          <svg class="i-info" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
            <path d="M16 14 L16 23 M16 8 L16 10" />
            <circle cx="16" cy="16" r="14" />
          </svg> подробности
        </a>
      </div>
    </div>
  </div>
</div>

templates/posts/includes/post_comment.html
{% load user_filters %}
<h4> Комментарии посетителей: </h4>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h6 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.get_full_name }}
        </a>
        <small> - {{ comment.created|date:"j M Y H:i:s" }}:
          {% if request.user.username == comment.author.username %}
            <a class="btn btn-primary btn-sm" href="{% url 'posts:del_comment' comment.id %}" title="Удалить комментарий">
              <svg class="i-trash" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                <path d="M28 6 L6 6 8 30 24 30 26 6 4 6 M16 12 L16 24 M21 12 L20 24 M11 12 L12 24 M12 6 L13 2 19 2 20 6" />
              </svg>
            </a>
          {% endif %}
          </small>
      </h6> 
      <p>
        {{ comment.text|linebreaksbr }}
      </p>      
    </div>
  </div>
{% empty %}
  Пока нет комментариев
{% endfor %} 

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">
      Добавить комментарий:
    </h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

templates/posts/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
  {% if user.is_authenticated %}
    <div class="row">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a 
            class="nav-link {% if view_name == 'posts:index' %}active{% endif %}"
            href="{% url 'posts:index' %}"
          >
            Все посты
          </a>
        </li>
        <li class="nav-item">
          <a 
            class="nav-link {% if view_name == 'posts:follow_index' %}active{% endif %}"
            href="{% url 'posts:follow_index' %}"
          >
            Подписки
          </a>
        </li>
        <li class="nav-item">
          <a 
            class="nav-link {% if view_name == 'posts:authors_list' %} active {% endif %}"
            href="{% url 'posts:authors_list' %}"
          >
            Авторы
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:groups' %} active {% endif %}"
             href="{% url 'posts:groups' %}"
          >
            Группы
          </a>
        </li>
      </ul>
    </div>
  {% endif %}
  {% if page_header %}
    <div class="row border-start border-end border-bottom rounded mb-4 shadow-sm">
      <div class="col p-4 d-flex flex-column">
        <h1 class="display-5 fw-bold text-center">
          {{ page_header }}
        </h1>
      </div>
    </div>
  {% endif %}
{% endwith %}